import { apiSlice } from "./apiSlice";
import { USER_URL } from "../constant";
// Define the userApiSlice with endpoints for user-related operations
export const userApiSlice = apiSlice.injectEndpoints({
    endpoints: (builder) => ({  //here the builder is used to define different types of endpoints like queries and mutations
        // Endpoint for user login
        login: builder.mutation({  //here the login is a mutation because it changes the state on the server
            query: (data) => ({    //here the data is the user credentials like email and password 
                //this will go to the endpoint http://localhost:5000/api/user/auth  in the backend 
                url: `${USER_URL}/auth`,
                method: 'POST',
                body: data,
            })
        }),
        register: builder.mutation({ //this is for the user registration
            query : (data) =>({
                url : `${USER_URL}`,
                method : 'POST',
                body : data,
            })
        }),
        logout : builder.mutation({
            query : (data) =>({
                url : `${USER_URL}/logout`,
                method : 'POST',
                body : data,
            })
        }),
        profile : builder.mutation({
            query : (data) =>({
                url : `${USER_URL}/profile`,  
                method : 'PUT',     // here we are using PUT method because we are updating the user profile in the backend 
                body : data,
            })
        }),
        //here we are fetching all user for the admin user to manage the users
        getusers : builder.query({  //here the getusers is a query because it is used to fetch the data from the server
            query : () =>({
                url : USER_URL,
            }),
            providesTags : ['User'], //this is used to invalidate the cache when the user data is updated    
            keepUnusedDataFor : 5, //this is used to keep the data in the cache for 5 seconds after the component is unmounted
        }),
        deleteuser : builder.mutation({
            query : (userId) =>({
                url : `${USER_URL}/${userId}`,
                method : 'DELETE',
            }),
        }),
        getUserDetails : builder.query({
            query : (userId) =>({
                url : `${USER_URL}/${userId}`,
            }),
            keepUnusedDataFor : 5, //this is used to keep the data in the cache for 5 seconds after the component is unmounted
        }),
        updateUser : builder.mutation({
            query : ({userId , ...data}) =>({ //here we are using destructuring to get the userId and the rest of the data
                url : `${USER_URL}/${userId}`,
                method : 'PUT',
                body : data,    //here the data is the user details like username , email , isAdmin etc except the userId
            }),
            invalidatesTags : ['User'], //this is used to invalidate the cache when the user data is updated
        })


    })
})

// `use${Login}Mutation`//this is a custom hook generated by RTK Query for the login mutation defined in the userApiSlice

export const { useLoginMutation } = userApiSlice; // Export the auto-generated hook for the login mutation
export const { useRegisterMutation } = userApiSlice; // Export the auto-generated hook for the register mutation
export const { useLogoutMutation } = userApiSlice; // Export the auto-generated hook for the logout mutation
export const { useProfileMutation } = userApiSlice; // Export the auto-generated hook for the profile mutation
export const { useGetusersQuery } = userApiSlice; // Export the auto-generated hook for the getusers query
export const { useDeleteuserMutation } = userApiSlice; // Export the auto-generated hook for the deleteuser mutation
export const { useGetUserDetailsQuery } = userApiSlice; // Export the auto-generated hook for the getUserDetails query
export const { useUpdateUserMutation } = userApiSlice; // Export the auto-generated hook for the updateUser mutation